"""
drive_cycles.py
================================================================================
Standard drive cycles (EPA UDDS / HWFET) as Altair Driver scenarios, for
EMS-efficiency campaigns.

The cycle's speed-vs-time trace becomes a closed-loop ADF: one maneuver in
which the driver follows a [DEMAND_SPEED] TYPE='CURVE' block pointing at a
[DEMAND_CURVE] time/velocity table (AKIMA-interpolated, velocities in mm/s
- confirmed against the stock scenarios: DEMAND VALUE 10000 mm/s = the
36 km/h double-lane entry speed). The deck's driver instantiates a feedback
PID traction controller for THROTTLE/BRAKE from this demand (observed in
the solver log), so the vehicle tracks the cycle.

Source data: EPA dynamometer schedules (cycles/uddscol.txt, cycles/
hwycol.txt) - two header lines, then tab-separated "seconds  mph".

speed-tracking RMSE between the MF4's VehicleSpeed and cycle_speed_kph()
is both a validity check and a drivability-adjacent metric.
================================================================================
"""

import os
import sys

MPH_TO_MMS = 447.04    # 1 mph = 0.44704 m/s
MPH_TO_KPH = 1.609344

CYCLES = {
    "UDDS": ("uddscol.txt", "EPA Urban Dynamometer Driving Schedule"),
    "HWFET": ("hwycol.txt", "EPA Highway Fuel Economy Test"),
}


def cycles_dir():
    if getattr(sys, "frozen", False):
        return os.path.join(sys._MEIPASS, "cycles")
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), "cycles")


def load_cycle(name):
    """-> (times_s, speeds_mph) from the EPA schedule file."""
    fname, _title = CYCLES[name.upper()]
    t, v = [], []
    with open(os.path.join(cycles_dir(), fname), encoding="utf-8") as fh:
        for line in fh.read().splitlines()[2:]:
            parts = line.split()
            if len(parts) >= 2:
                t.append(float(parts[0]))
                v.append(float(parts[1]))
    if not t:
        raise ValueError("no data parsed from cycle file " + fname)
    return t, v


def cycle_speed_kph(name):
    """-> (times_s, speeds_kph) - the reference trace for tracking checks."""
    t, v = load_cycle(name)
    return t, [x * MPH_TO_KPH for x in v]


def build_cycle_adf(name, hmax=0.01, print_interval=0.01, t_max=None):
    """Full ADF text for a closed-loop drive-cycle scenario. t_max truncates
    the cycle (smoke tests); None runs the whole schedule."""
    name = name.upper()
    fname, title = CYCLES[name]
    t, v = load_cycle(name)
    if t_max is not None:
        keep = [i for i, x in enumerate(t) if x <= t_max]
        t, v = [t[i] for i in keep], [v[i] for i in keep]
    return build_adf_from_series(name, title, t,
                                 [x * MPH_TO_MMS for x in v],
                                 hmax=hmax, print_interval=print_interval)


def build_adf_from_series(name, title, t_s, v_mms, hmax=0.01,
                          print_interval=0.01):
    """Closed-loop speed-following ADF from an arbitrary time/velocity
    series (velocities in mm/s). Shared by the EPA cycles and the
    real-drive importer's speed-only mode."""
    sim_time = t_s[-1]
    rows = "\n".join(" {:<16} {:<15}".format(round(float(ts), 2),
                                             round(float(vs), 2))
                     for ts, vs in zip(t_s, v_mms))

    return """$-----------------------------------------------------------------------ALTAIR_HEADER
[ALTAIR_HEADER]
FILE_TYPE    = 'ADF'
FILE_VERSION = 2.0
FILE_FORMAT  = 'ASCII'
$ Scenario: {name} — {title} ({n} points, {sim:.0f} s) — generated by SimBuilder
$-------------------------------------------------------------------------------UNITS
[UNITS]
(BASE)
{{ length  force         angle           mass     time }}
  'mm'   'newton'      'radians'        'kg'    'sec'
$--------------------------------------------------------------------------VEHICLE_IC
[VEHICLE_INITIAL_CONDITIONS]
VX0               = {vx0:.2f}
VY0               = 0.0
VZ0               = 0.0
ENGINE_INIT_SPEED = 300
$----------------------------------------------------------------------STEER_STANDARD
[STEER_STANDARD]
MAX_VALUE            = 9.4248
MIN_VALUE            = -9.4248
SMOOTHING_FREQUENCY  = 10
INITIAL_VALUE        = 0
$-------------------------------------------------------------------THROTTLE_STANDARD
[THROTTLE_STANDARD]
MAX_VALUE            = 1
MIN_VALUE            = 0
SMOOTHING_FREQUENCY  = 10
INITIAL_VALUE        = 0
$----------------------------------------------------------------------BRAKE_STANDARD
[BRAKE_STANDARD]
MAX_VALUE            = 1
MIN_VALUE            = 0
SMOOTHING_FREQUENCY  = 10
INITIAL_VALUE        = 0
$-----------------------------------------------------------------------GEAR_STANDARD
[GEAR_STANDARD]
MAX_VALUE            = 6
MIN_VALUE            = 1
SMOOTHING_FREQUENCY  = 10
INITIAL_VALUE        = 1
$---------------------------------------------------------------------CLUTCH_STANDARD
[CLUTCH_STANDARD]
MAX_VALUE            = 1
MIN_VALUE            = 0
SMOOTHING_FREQUENCY  = 10
INITIAL_VALUE        = 0
$----------------------------------------------------------------------MANEUVERS_LIST
[MANEUVERS_LIST]
{{name            simulation_time      h_max           print_interval }}
'MANEUVER_1'     {sim:.0f}                  {hmax:g}           {pint:g}
$--------------------------------------------------------------------------MANEUVER_1
[MANEUVER_1]
TASK = 'STANDARD'
(CONTROLLERS)
{{DRIVER_SIGNAL             PRIMARY_CONTROLLER        ADDITIONAL_CONTROLLER    }}
 STEER                     OL_STEER                  NONE
 THROTTLE                  FF_TRACTION_CONTROLLER    NONE
 BRAKE                     FF_TRACTION_CONTROLLER    NONE
 GEAR                      GEAR_CLUTCH_CONTROL       NONE
 CLUTCH                    GEAR_CLUTCH_CONTROL       NONE
$-----------------------------------------------------------FF_TRACTION_CONTROLLER
[FF_TRACTION_CONTROLLER]
TAG                    = 'FEEDFORWARD'
TYPE                   = 'FOLLOW_VELOCITY'
LOOK_AHEAD_TIME        = 0.5
DEMAND_SIGNAL          = 'DEMAND_SPEED'
$-----------------------------------------------------------DEMAND_SPEED
[DEMAND_SPEED]
TYPE  = 'CURVE'
BLOCK = 'DEMAND_CURVE'
$-----------------------------------------------------------DEMAND_CURVE
[DEMAND_CURVE]
INDEPENDENT_VARIABLE = 'TIME'
DEPENDENT_VARIABLE   = 'VELOCITY'
INTERPOLATION        = 'AKIMA'
{{TIME            VELOCITY       }}
{rows}
$----------------------------------------------------------------------------OL_STEER
[OL_STEER]
TAG                    = 'OPENLOOP'
TYPE                   = 'CONSTANT'
VALUE                  = 0
$----------------------------------------------------------------%GEAR_CLUTCH_CONTROL
$Used in case of models with IC Engine
[GEAR_CLUTCH_CONTROL]
TAG = 'ENGINE_SPEED'
(GEAR_SHIFT_MAP)
{{G   US      DS      CT      CRT     TFD     TFT     CFT     TRD     TRT}}
 1   650     125     0.45    0.05    0.1     0.1     0.05    0.05    0.05
 2   650     125     0.45    0.05    0.1     0.1     0.05    0.05    0.05
 3   650     125     0.45    0.05    0.1     0.1     0.05    0.05    0.05
 4   650     125     0.45    0.05    0.1     0.1     0.05    0.05    0.05
 5   650     125     0.45    0.05    0.1     0.1     0.05    0.05    0.05
""".format(name=name, title=title, n=len(t_s), sim=sim_time,
           # creep-start floor: the LYRIQ deck cannot initialize at exactly
           # v=0 (first-step DASPK failure, any configuration - bisected
           # 2026-07-17). 250 mm/s = 0.9 km/h initializes fine; the driver
           # immediately regulates to the demanded trace (UDDS/HWFET start
           # at 0, so they hit this floor by design).
           vx0=max(float(v_mms[0]), 250.0), hmax=hmax, pint=print_interval,
           rows=rows)
