"""sweep_events.py - generate the AVL-Drive sweep events (Bible 30.10).
Three composite ADFs built on the AVLlit template's header/standards/tail,
so every proven grammar element is reused verbatim:
  open-loop pedal  : OPENLOOP EXPRESSION STEP({%TIME},t0,h0,t1,h1), SIGNAL_CHANNEL 0
  open-loop brake  : OPENLOOP CONSTANT (never EXPRESSION - channel-0 hijack)
  cruise hold      : PID FOLLOW_VELOCITY (Kp 0.3 Ki 0.05) on a CONSTANT demand
  end conditions   : LONG_VEL GT/LT in mm/s
Usage: python sweep_events.py  -> writes rl_gym/sweep/<event>.adf"""
import json
import os
import re

_lc = {}
try:
    _lc = json.load(open(os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), "vehicle_local.json")))
except Exception:
    pass
DATA_ROOT = _lc.get("data_root", "C:/demo_data")
TEMPLATE = DATA_ROOT + "/avl_regenoff_runs/AVLlit_tipin_50pct_20260726_075106/custom_event_tipout_10.adf"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sweep")

KPH = 1000.0 / 3.6   # mm/s per km/h
CTRL_OL = ("(CONTROLLERS)\n"
           "{DRIVER_SIGNAL             PRIMARY_CONTROLLER        ADDITIONAL_CONTROLLER    }\n"
           " STEER                     OL_STEER                  NONE                     \n"
           " THROTTLE                  OL_THROTTLE_%d             NONE                     \n"
           " BRAKE                     OL_BRAKE_%d                NONE                     \n"
           " GEAR                      GEAR_CLUTCH_CONTROL       NONE                     \n"
           " CLUTCH                    GEAR_CLUTCH_CONTROL       NONE                     \n")
CTRL_PID = ("(CONTROLLERS)\n"
            "{DRIVER_SIGNAL             PRIMARY_CONTROLLER        ADDITIONAL_CONTROLLER    }\n"
            " STEER                     OL_STEER                  NONE                     \n"
            " THROTTLE                  PID_TRACTION_%d            NONE                     \n"
            " BRAKE                     PID_TRACTION_%d            NONE                     \n"
            " GEAR                      GEAR_CLUTCH_CONTROL       NONE                     \n"
            " CLUTCH                    GEAR_CLUTCH_CONTROL       NONE                     \n")


def sep(name):
    return "$" + "-" * max(1, 84 - len(name)) + name + "\n"


def end_cond(op, kph, tol_kph):
    return ("(END_CONDITIONS) \n"
            "{SIGNAL     GROUP      ABS        OPERATOR   VALUE      TOLERANCE  WATCH_TIME}\n"
            " LONG_VEL   0          Y          %-10s %-10.3f %-10.3f 0.001     \n"
            % (op, kph * KPH, tol_kph * KPH))


class Event:
    def __init__(self, name, vx0_mm=10):
        self.name, self.vx0, self.m = name, vx0_mm, []

    # --- maneuver kinds ---
    def hold(self, secs, brake):
        """standstill: pedal 0, brake held"""
        self.m.append(dict(kind="ol", secs=secs, thr="0", thr_const=True, brake=brake, end=None))

    def pedal(self, secs, target, hold_from="{THROTTLE_0}", delay=1.0, brake=0, end=None):
        """open-loop pedal step: hold current pedal `delay` s, then 0.3 s ramp to target (0-1)"""
        expr = "STEP({%%TIME},%g,%s,%g,%.4f)" % (delay, hold_from, delay + 0.3, target)
        self.m.append(dict(kind="ol", secs=secs, thr=expr, thr_const=False, brake=brake, end=end))

    def stop(self, secs, brake):
        """open-loop brake to (near) standstill"""
        self.m.append(dict(kind="ol", secs=secs, thr="0", thr_const=True, brake=brake,
                           end=("LT", 0.7, 0.4)))

    def cruise(self, secs, kph):
        """closed-loop speed hold (PID follow)"""
        self.m.append(dict(kind="pid", secs=secs, kph=kph))

    # --- render ---
    def render(self, template):
        head = template[:template.index("[MANEUVERS_LIST]")]
        head = re.sub(r"(VX0\s*=\s*)\S+", r"\g<1>%d" % self.vx0, head)
        head = head.replace("$ Scenario: AVLlit_tipin_50pct - tip-in/out 50% pedal (REGEN-OFF: lift to coast pedal, 5s standstill dwell)",
                            "$ Scenario: %s - AVL-Drive sweep event (generated by sweep_events.py)" % self.name)
        # fixed tail = from the OL_STEER separator line to the end (OL_STEER + GEAR_CLUTCH_CONTROL)
        tail = template[re.search(r"\$-+OL_STEER\s*\n\[OL_STEER\]", template).start():]
        out = head
        out += sep("MANEUVERS_LIST") + "[MANEUVERS_LIST]\n{name            simulation_time      h_max           print_interval }\n"
        for i, mv in enumerate(self.m, 1):
            out += "'MANEUVER_%d'     %-20g 0.01            0.01            \n" % (i, mv["secs"])
        for i, mv in enumerate(self.m, 1):
            out += sep("MANEUVER_%d" % i) + "[MANEUVER_%d]\nTASK = 'STANDARD'\n" % i
            if mv["kind"] == "ol":
                out += CTRL_OL % (i, i)
                if mv["end"]:
                    out += end_cond(*mv["end"])
                out += sep("OL_THROTTLE_%d" % i) + "[OL_THROTTLE_%d]\nTAG                    = 'OPENLOOP'\n" % i
                if mv["thr_const"]:
                    out += "TYPE                   = 'CONSTANT'\nVALUE                  = %s\n" % mv["thr"]
                else:
                    out += ("TYPE                   = 'EXPRESSION'\nEXPRESSION             = '%s'\n"
                            "SIGNAL_CHANNEL         = 0\n" % mv["thr"])
                out += sep("OL_BRAKE_%d" % i) + ("[OL_BRAKE_%d]\nTAG                    = 'OPENLOOP'\n"
                                                "TYPE                   = 'CONSTANT'\nVALUE                  = %g\n" % (i, mv["brake"]))
            else:
                out += CTRL_PID % (i, i)
                out += sep("PID_TRACTION_%d" % i) + ("[PID_TRACTION_%d]\nTAG                    = 'PID'\n"
                                                    "TYPE                   = 'FOLLOW_VELOCITY'\n"
                                                    "DEMAND_SIGNAL          = 'DEMAND_SPEED_%d'\n"
                                                    "KP                     = 0.3\nKI                     = 0.05\n"
                                                    "KD                     = 0\n" % (i, i))
                out += sep("DEMAND_SPEED_%d" % i) + ("[DEMAND_SPEED_%d]\nTYPE  = 'CONSTANT'\n"
                                                    "VALUE = %.1f\n" % (i, mv["kph"] * KPH))
        out += tail
        return out


def build():
    T = open(TEMPLATE, encoding="utf-8", errors="replace").read()
    os.makedirs(OUT, exist_ok=True)
    ev = []
    # 1) driveaway family: 20 / 40 / 70 / 100 % from brake-held standstill
    # brake fraction ~ decel/g on this deck (0.5 gave -5.2 m/s2, a locked-wheel
    # stop that left the body rocking at +/-4.5 m/s2 into the next launch and
    # killed the run - 2026-09-02). Driveaway-family stops are gentle: 0.2.
    d = Event("sweep_driveaway")
    d.hold(5, 0.35)
    for ped, target in ((0.20, 15), (0.40, 30), (0.70, 40), (1.00, 50)):
        d.pedal(45, ped, hold_from="0", end=("GT", target, 1.0))
        d.stop(40, 0.2)
        d.hold(4, 0.35)
    ev.append(d)
    # 2) tip-in / tip-out ladder around closed-loop cruise holds
    l = Event("sweep_tipin_ladder")
    l.hold(5, 0.35)
    l.cruise(25, 30)
    l.pedal(20, 0.50, end=("GT", 50, 2.5))
    l.cruise(15, 50)
    l.pedal(20, 1.00, end=("GT", 80, 2.5))
    l.cruise(15, 80)
    l.pedal(6, 0.00)                 # lift-off tip-out at 80
    l.cruise(12, 80)
    l.pedal(8, 0.25)                 # mild tip-in at 80
    l.cruise(20, 100)
    l.pedal(6, 0.00)                 # lift-off tip-out at 100
    l.cruise(8, 100)
    ev.append(l)
    # 3) coast-down and braking stops
    c = Event("sweep_coast_brake")
    c.hold(5, 0.35)
    c.cruise(40, 100)
    c.pedal(150, 0.00, end=("LT", 5, 1.0))   # lift at 100 -> regen coast to 5 km/h
    c.cruise(25, 80)
    c.stop(40, 0.2)                          # moderate stop from 80 (~2 m/s2)
    c.hold(4, 0.35)
    c.cruise(20, 50)
    c.stop(30, 0.4)                          # firm stop from 50 (~4 m/s2)
    c.hold(4, 0.35)
    ev.append(c)
    for e in ev:
        p = os.path.join(OUT, e.name + ".adf")
        open(p, "w", encoding="utf-8").write(e.render(T))
        cap = sum(mv["secs"] for mv in e.m)
        print("%-20s %2d maneuvers, time cap %4.0f s -> %s" % (e.name, len(e.m), cap, p))


if __name__ == "__main__":
    build()
